"""initial_migration

Revision ID: 19ff03ff2ceb
Revises:
Create Date: 2026-05-03 09:38:37.275438
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "19ff03ff2ceb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academy_categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_academy_categories_name"), "academy_categories", ["name"], unique=True)
    op.create_index(op.f("ix_academy_categories_slug"), "academy_categories", ["slug"], unique=True)
    op.create_table(
        "companies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("website_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("domain", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "company_type",
            sa.Enum(
                "training_center",
                "school",
                "cfa",
                "university",
                "pme",
                "startup",
                "web_agency",
                "it_company",
                "recruiter",
                "public_organization",
                "nonprofit",
                "enterprise",
                "unknown",
                name="companytype",
            ),
            nullable=False,
        ),
        sa.Column("sector", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("size_label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("employee_count", sa.Integer(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "france_travail",
                "company_website",
                "linkedin_manual",
                "csv",
                "hunter",
                "dropcontact",
                "soria_website_form",
                "academy",
                "openproject",
                "other",
                name="sourcetype",
            ),
            nullable=False,
        ),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "to_review",
                "qualified",
                "not_relevant",
                "contacted",
                "active_opportunity",
                "closed",
                name="companystatus",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_companies_domain"), "companies", ["domain"], unique=False)
    op.create_index(op.f("ix_companies_name"), "companies", ["name"], unique=False)
    op.create_index(op.f("ix_companies_slug"), "companies", ["slug"], unique=True)
    op.create_table(
        "service_categories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("status", sa.Enum("active", "inactive", name="servicecategorystatus"), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_service_categories_name"), "service_categories", ["name"], unique=True)
    op.create_index(op.f("ix_service_categories_slug"), "service_categories", ["slug"], unique=True)
    op.create_table(
        "source_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "manual",
                "france_travail",
                "company_website",
                "linkedin_manual",
                "csv",
                "hunter",
                "dropcontact",
                "soria_website_form",
                "academy",
                "openproject",
                "other",
                name="sourcetype",
            ),
            nullable=False,
        ),
        sa.Column("source_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("processing_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_records_external_id"), "source_records", ["external_id"], unique=False)
    op.create_table(
        "academy_resources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("short_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "resource_type",
            sa.Enum(
                "guide",
                "article",
                "checklist",
                "course",
                "lab",
                "workshop",
                "project",
                "moodle_path",
                "support_material",
                "case_study",
                name="academyresourcetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "level", sa.Enum("beginner", "intermediate", "advanced", "mixed", name="academylevel"), nullable=False
        ),
        sa.Column("target_audience", sa.JSON(), nullable=True),
        sa.Column("technologies", sa.JSON(), nullable=True),
        sa.Column("public_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("academy_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("moodle_course_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_free", sa.Boolean(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["academy_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_academy_resources_slug"), "academy_resources", ["slug"], unique=True)
    op.create_index(op.f("ix_academy_resources_title"), "academy_resources", ["title"], unique=False)
    op.create_table(
        "contacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("role_title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("linkedin_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "contact_type",
            sa.Enum(
                "director",
                "training_manager",
                "it_manager",
                "hr",
                "recruiter",
                "technical_lead",
                "founder",
                "generic_contact",
                "academic_contact",
                "unknown",
                name="contacttype",
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "france_travail",
                "company_website",
                "linkedin_manual",
                "csv",
                "hunter",
                "dropcontact",
                "soria_website_form",
                "academy",
                "openproject",
                "other",
                name="sourcetype",
            ),
            nullable=False,
        ),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "email_verification_status",
            sa.Enum("unknown", "not_checked", "valid", "invalid", "risky", name="emailverificationstatus"),
            nullable=False,
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("opt_out", sa.Boolean(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contacts_email"), "contacts", ["email"], unique=False)
    op.create_index(op.f("ix_contacts_full_name"), "contacts", ["full_name"], unique=False)
    op.create_table(
        "offers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("short_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_audience", sa.JSON(), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=True),
        sa.Column("landing_page_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["service_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_offers_name"), "offers", ["name"], unique=False)
    op.create_index(op.f("ix_offers_slug"), "offers", ["slug"], unique=True)
    op.create_table(
        "opportunities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("offer_id", sa.Uuid(), nullable=True),
        sa.Column("academy_resource_id", sa.Uuid(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "opportunity_type",
            sa.Enum(
                "formation",
                "devops_cloud",
                "cybersecurity_soc",
                "iam_sso",
                "monitoring",
                "freelance",
                "job",
                "academic",
                "partnership",
                "academy",
                "other",
                name="opportunitytype",
            ),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("detected_need", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "france_travail",
                "company_website",
                "linkedin_manual",
                "csv",
                "hunter",
                "dropcontact",
                "soria_website_form",
                "academy",
                "openproject",
                "other",
                name="sourcetype",
            ),
            nullable=False,
        ),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "to_analyze",
                "scored",
                "interesting",
                "not_relevant",
                "contact_to_find",
                "contact_found",
                "draft_needed",
                "draft_ready",
                "waiting_validation",
                "approved",
                "sent",
                "follow_up_needed",
                "response_received",
                "meeting_scheduled",
                "converted",
                "lost",
                "closed",
                name="opportunitystatus",
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.Enum("low", "medium", "high", "urgent", name="opportunitypriority"), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("recommended_landing_page", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("next_action", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["academy_resource_id"],
            ["academy_resources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_opportunities_title"), "opportunities", ["title"], unique=False)
    op.create_table(
        "compliance_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("opportunity_id", sa.Uuid(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum(
                "contact_collected",
                "email_verified",
                "message_generated",
                "message_approved",
                "message_sent",
                "opt_out_requested",
                "data_deleted",
                name="complianceeventtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "france_travail",
                "company_website",
                "linkedin_manual",
                "csv",
                "hunter",
                "dropcontact",
                "soria_website_form",
                "academy",
                "openproject",
                "other",
                name="sourcetype",
            ),
            nullable=False,
        ),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reason_for_contact", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("professional_relevance", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("opt_out_status", sa.Boolean(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "follow_ups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "send_first_message",
                "send_follow_up",
                "call",
                "linkedin_manual_message",
                "prepare_proposal",
                "schedule_meeting",
                "update_openproject",
                "close_opportunity",
                name="followupactiontype",
            ),
            nullable=False,
        ),
        sa.Column("status", sa.Enum("planned", "done", "cancelled", "overdue", name="followupstatus"), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("openproject_work_package_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "interactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column(
            "interaction_type",
            sa.Enum("email", "linkedin", "phone", "meeting", "note", "system_event", name="interactiontype"),
            nullable=False,
        ),
        sa.Column("direction", sa.Enum("inbound", "outbound", "internal", name="interactiondirection"), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("happened_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message_drafts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column(
            "message_type",
            sa.Enum(
                "prospecting_email",
                "linkedin_message",
                "follow_up_email",
                "training_proposal",
                "devops_proposal",
                "cybersecurity_proposal",
                "academy_invitation",
                "motivation_letter",
                "cv_summary",
                "internal_note",
                name="messagetype",
            ),
            nullable=False,
        ),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "needs_review",
                "approved",
                "rejected",
                "sent_manually",
                "sent_by_system",
                "archived",
                name="messagestatus",
            ),
            nullable=False,
        ),
        sa.Column("generated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("prompt_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("review_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "opportunity_scores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column("training_score", sa.Integer(), nullable=False),
        sa.Column("devops_score", sa.Integer(), nullable=False),
        sa.Column("security_score", sa.Integer(), nullable=False),
        sa.Column("business_score", sa.Integer(), nullable=False),
        sa.Column("academy_score", sa.Integer(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=True),
        sa.Column("scoring_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("opportunity_scores")
    op.drop_table("message_drafts")
    op.drop_table("interactions")
    op.drop_table("follow_ups")
    op.drop_table("compliance_events")
    op.drop_index(op.f("ix_opportunities_title"), table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index(op.f("ix_offers_slug"), table_name="offers")
    op.drop_index(op.f("ix_offers_name"), table_name="offers")
    op.drop_table("offers")
    op.drop_index(op.f("ix_contacts_full_name"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_email"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_academy_resources_title"), table_name="academy_resources")
    op.drop_index(op.f("ix_academy_resources_slug"), table_name="academy_resources")
    op.drop_table("academy_resources")
    op.drop_index(op.f("ix_source_records_external_id"), table_name="source_records")
    op.drop_table("source_records")
    op.drop_index(op.f("ix_service_categories_slug"), table_name="service_categories")
    op.drop_index(op.f("ix_service_categories_name"), table_name="service_categories")
    op.drop_table("service_categories")
    op.drop_index(op.f("ix_companies_slug"), table_name="companies")
    op.drop_index(op.f("ix_companies_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_domain"), table_name="companies")
    op.drop_table("companies")
    op.drop_index(op.f("ix_academy_categories_slug"), table_name="academy_categories")
    op.drop_index(op.f("ix_academy_categories_name"), table_name="academy_categories")
    op.drop_table("academy_categories")
    # ### end Alembic commands ###
